version: '3.8'
services:
  api:
    container_name: nestjsca_api
    build: 
      context: ./../../../
      dockerfile: ./docker/file/nodejs/local.Dockerfile
    image: scm.salt.id:5050/tommyprmbd/nestjs-clean-architecture-starter:dev
    volumes:
      - ./../../../:/app/
    ports:
      - ${DOCKER_NODE_BIND_PORT}:3000
    depends_on:
      - db
      - cache
    networks:
      nestjsca_network:
        ipv4_address: ${DOCKER_NODE_IP_ADDRESS}

  db:
    container_name: nestjsca_db
    image: mysql:latest
    ports:
      - ${DOCKER_MYSQL_BIND_PORT}:3306
    volumes:
      - ./../../data/mysql:/var/lib/mysql
    command: 
      --bind-address=0.0.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      nestjsca_network:
        ipv4_address: ${DOCKER_MYSQL_IP_ADDRESS}

  cache:
    container_name: nestjsca_cache
    image: redis:alpine
    ports:
      - ${DOCKER_REDIS_BIND_PORT}:6379
    volumes:
      - ./../../data/cache:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass P@ssw0rd
    networks:
      nestjsca_network:
        ipv4_address: ${DOCKER_REDIS_IP_ADDRESS}

networks:
  nestjsca_network:
    ipam:
      config:
        - subnet: ${DOCKER_NETWORK_SUBNET}