export enum DbConfigEnum {
  DB_TYPE = 'DB_TYPE',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_NAME = 'DB_NAME',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  IS_SYNC = 'IS_SYNC',
  IS_AUTOLOAD_ENTITIES = 'IS_AUTOLOAD_ENTITIES',
}
